#server:
#  port: 8084
#  
#spring:
#  application:
#    name: API-GATEWAY
#    
#
#  cloud:
#    gateway:
#      routes:
#      - id: USER-SERVICE
#        uri: lb://USER-SERVICE
#        predicates:
#        - Path=/users/**
#        
#      - id: HOTEL-SERVICE
#        uri: lb://HOTEL-SERVICE
#        predicates:
#        - Path=/hotels/**
#        
#        
#      - id: RATING-SERVICE
#        uri: lb://RATING-SERVICE
#        predicates:
#        - Path=/ratings/** 
#        
#    
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defalutZone: http://localhost:8761/eureka



server:
  port: 9091
  
spring:
  application:
    name: GATEWAY
    

  cloud:
    gateway:
      routes:
      - id: PASSENGER-SERVICE
        uri: lb://PASSENGER-SERVICE
        predicates:
        - Path=/passengers/**
        
      - id: TICKET-SERVICE
        uri: lb://TICKET-SERVICE
        predicates:
        - Path=/tickets/**
        
        
      - id: TRAIN-SERVICE
        uri: lb://TRAIN-SERVICE
        predicates:
        - Path=/trains/** 
        
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defalutZone: http://localhost:8761/eureka



